spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    h2:
      console:
        enabled: true
        path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

scrap:
  url: https://codetest-v4.3o3.co.kr/scrap
  header:
    key: X-API-KEY
    value: fQL4PtoGRRgj6Q1OZG1WpQ==