spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    h2:
      console:
        enabled: true
        path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#  mvc:
#    servlet:
#      path: /szs

logging.level:
  com.example.szs: debug
  org:
    springframework:
      security=TRACE:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem

scrap:
  url: https://codetest-v4.3o3.co.kr/scrap
  header:
    key: X-API-KEY
    value: fQL4PtoGRRgj6Q1OZG1WpQ==

jwt:
  secret: 8962312ec726ed9a9916057ee731530b24c24561083f0ba4156266dfbbfb6341

# 6시간(1000 * 60 * 60 * 6L)
ACCESS_TOKEN_EXPIRE_TIME: 21600000

# 2달(1000 * 60 * 60 * 24 * 60L)
REFRESH_TOKEN_EXPIRE_TIME: 5184000000

# 2주(1000 * 60 * 60 * 24 * 14L)
REFRESH_TOKEN_REISSUE_TIME : 1209600000


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access.ExceptionTranslationFilter: TRACE
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: TRACE
    org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter: DEBUG


# Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /3o3/swagger.html
    enabled: true
#  api-docs:
#    groups:
#      enabled: true
#  swagger-ui:
#    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
#    tags-sorter: alpha # 태그 정렬 기준
#    path: /swagger.html # html 문서 접속 경로
#    disable-swagger-default-url: true
#    display-query-params-without-oauth2: true
#    doc-expansion: none # tag, operation 펼치는 방식
#  packages-to-scan: com.example.szs.controller